---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 5080, host: 5080}]
    - ["forwarded_port", {guest: 5081, host: 5081}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[flapjack_test]
      - recipe[flapjack]
    attributes:
      flapjack:
        install_ruby: false
        ruby_bin_dir: /opt/chef/embedded/bin
        contacts:
          manage_all_entity: true
  - name: package
    run_list:
      - recipe[flapjack_test]
      - recipe[flapjack]
    attributes:
      flapjack:
        install_method: package
        version: '1.5.0'
