#!/usr/bin/env ruby
#^syntax detection

site "http://community.opscode.com/api/v1"

cookbook "ubuntu"
cookbook "yum-epel"

cookbook "package_installer"

cookbook "ruby_installer", :git => "https://github.com/hw-cookbooks/ruby_installer.git", :ref => "develop"

cookbook "flapjack", :path => "."
