name             'flapjack_test'
maintainer       'Heavy Water Operations, LLC.'
maintainer_email 'support@hw-ops.com'
license          'MIT'
description      'Installs/Configures flapjack_test'
version          '0.1.0'

depends 'ubuntu'
depends 'yum-epel'
depends 'package_installer'
